services:
  app:
    build:
      context: .
      args:
        BASE_IMAGE: python:3.13-slim
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: strava_activity
      POSTGRES_USER: user_qwerty
      POSTGRES_PASSWORD: qwerty1234
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_qwerty -d qa_test_generator"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pg_data:
  redis_data:

