@startuml

title Обновление рекомендаций

actor Client
participant Web
participant Orchestrator
participant RecommendationUpdater
participant RecommedationsGetterJob
participant RecommendationsGetter
participant RedisClient

Client -> Web : Получить \nрекомендации
Web -> Orchestrator : update_recommedations()

Orchestrator -> RecommendationUpdater ++ #SkyBlue : call(user_id)
RecommendationUpdater -> RecommedationsGetterJob : perform_async(user_id)
deactivate RecommendationUpdater

Orchestrator -> RecommendationsGetter ++ #SkyBlue : get_recommendations(user_id)
RecommendationsGetter -> RedisClient : get(user_id)
RecommendationsGetter <-- RedisClient : recommendations
Orchestrator <-- RecommendationsGetter -- : recommendations

Web <-- Orchestrator : athlete_activities()
Client <-- Web : Отображение \nсписка \nтренировок

@enduml
