@startuml

title Взаимодействие компонентов системы

actor "Пользователь" as Client
participant "Приложение анализатор" as Application
participant "Strava API" as Strava
participant "Кэш Redis" as Redis
participant "API для классификации" as CatAPI
database "База данных" as DB

Client -> Application: Пользователь заходит в приложение
Application -> Strava: Авторизация через Strava
Application <-- Strava: Успешная авторизация, \nполучение access и refresh токенов
Application -> Redis: Сохранение токенов в кэш
Application <-- Redis: Получение токенов из кэша
Application -> Strava: Запрос на получение \nпоследних тренировок из Strava \nпо авторизованному пользователю
Application <-- Strava: Получение тренировок (синхронизация)
Application -> Strava: Запрос на получение данных об авторизованном пользователе
Application <-- Strava: Получение данных о пользователе
Application -> DB: Запись данных полученных тренировок
Application -> DB: Запись данных о пользователе / обновление данных
Application -> CatAPI: Запрос на классификацию полученных новых тренировок из Strava
Application <-- CatAPI: Список тренировок с предсказанным типом мощности и показателем интенсивности
Application -> DB: Обновление данных по тренировкам: заполнение типа мощности и показателя интенсивности
Application <-- DB: Получение списка тренировок с показателями физической активности
Application <-- DB: Получение данных о пользователе
Client <-- Application: Показ списка тренировок пользователю

@enduml
