@startuml

title Просмотр одной тренировки

actor Client
participant Web
participant Orchestrator
participant StravaFetchOneActivity
participant Repository
database DB 

Client -> Web : Просмотр \nтренировок
Web -> Orchestrator : activity(activity_id)
Orchestrator -> StravaFetchOneActivity ++ #SkyBlue : call(current_user_id, activity_id)
StravaFetchOneActivity -> Repository ++ #SkyBlue : fetch_one_by_id_and_user_id(user_id, activity_id)
Repository -> DB
Repository <-- DB
StravaFetchOneActivity <-- Repository -- : activity
Orchestrator <-- StravaFetchOneActivity -- : activity

Web <-- Orchestrator : activity(activity_id)
Client <-- Web : Отображение \nконкретной \nтренировки

@enduml
