@startuml

title Просмотр одной тренировки

actor Client
participant Web
participant Orchestrator
participant StravaFetchOneActivity
participant ActivitiesRepository
database DB 

Client -> Web : Просмотр тренировок
Web -> Orchestrator : activity(activity_id)
Orchestrator -> StravaFetchOneActivity ++ #SkyBlue : call(current_user_id, activity_id)
StravaFetchOneActivity -> ActivitiesRepository ++ #SkyBlue : fetch_one_by_id_and_user_id(user_id, activity_id)
ActivitiesRepository -> DB
ActivitiesRepository <-- DB
StravaFetchOneActivity <-- ActivitiesRepository -- : activity
Orchestrator <-- StravaFetchOneActivity -- : activity

Web <-- Orchestrator : activity(activity_id)
Client <-- Web : Отображение конкретной тренировки

@enduml
